# Generated by Django 6.0.3 on 2026-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_frota', models.CharField(choices=[('Própria', 'Própria'), ('Agregado', 'Agregado')], max_length=20, verbose_name='Frota (Própria ou Agregado)')),
                ('condutor', models.CharField(max_length=150, verbose_name='Condutor')),
                ('cnh_upload', models.FileField(blank=True, null=True, upload_to='documentos/cnh/', verbose_name='Upload da CNH')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('crlv_upload', models.FileField(blank=True, null=True, upload_to='documentos/crlv/', verbose_name='Upload do CRLV')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano Fabricação')),
                ('ano_modelo', models.IntegerField(verbose_name='Ano Modelo')),
                ('seguradora', models.CharField(max_length=100, verbose_name='Seguradora')),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('dia_vencimento', models.IntegerField(verbose_name='Dia do Primeiro Vencimento')),
                ('numero_parcelas', models.IntegerField(verbose_name='Número de Parcelas')),
                ('tipo_cobertura', models.CharField(max_length=50, verbose_name='Tipo de Cobertura')),
                ('franquia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Franquia')),
                ('danos_materiais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Danos Materiais')),
                ('danos_corporais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Danos Corporais')),
                ('danos_morais', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Danos Morais')),
                ('app_morte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='APP Morte')),
                ('app_invalidez', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='APP Invalidez')),
                ('assistencia_km', models.IntegerField(verbose_name='Assistência 24 Horas (KM)')),
                ('carro_reserva_dias', models.IntegerField(verbose_name='Carro Reserva (Dias)')),
                ('vidros', models.BooleanField(default=False, verbose_name='Vidros (Sim/Não)')),
            ],
        ),
    ]
