# Generated by Django 6.0.3 on 2026-03-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FROTA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='APP_FROTA.veiculo')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
