# Generated by Django 6.0.3 on 2026-03-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FROTA', '0002_veiculohistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cnh_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnh/', verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='crlv_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos/crlv/', verbose_name='CRLV'),
        ),
    ]
