# Generated by Django 6.0.3 on 2026-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FROTA', '0003_alter_veiculo_cnh_upload_alter_veiculo_crlv_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='Número da CNH')),
                ('validade_cnh', models.DateField(verbose_name='Validade da CNH')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='condutor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Condutor'),
        ),
    ]
