# Generated by Django 6.0.3 on 2026-03-06 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FROTA', '0004_condutor_alter_veiculo_condutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='condutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='APP_FROTA.condutor', verbose_name='Condutor'),
        ),
    ]
