# Generated by Django 6.0.3 on 2026-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FROTA', '0005_alter_veiculo_condutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='cnh_upload',
        ),
        migrations.AddField(
            model_name='condutor',
            name='cnh_upload',
            field=models.FileField(blank=True, null=True, upload_to='documentos/cnh/', verbose_name='CNH'),
        ),
    ]
