# Generated by Django 6.0.3 on 2026-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_FROTA', '0006_remove_veiculo_cnh_upload_condutor_cnh_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='dia_vencimento',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_primeiro_vencimento',
            field=models.DateField(default='2026-03-06', verbose_name='Data do Primeiro Vencimento'),
            preserve_default=False,
        ),
    ]
